// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package api

// AddLensBody defines model for AddLensBody.
type AddLensBody struct {
	Description *string   `json:"description,omitempty"`
	Owner       *string   `json:"owner,omitempty"`
	Spec        *string   `json:"spec,omitempty"`
	Tags        *[]string `json:"tags,omitempty"`
}

// Lens defines model for Lens.
type Lens struct {
	Description *string   `json:"description,omitempty"`
	Id          *string   `json:"id,omitempty"`
	Name        *string   `json:"name,omitempty"`
	Owner       *string   `json:"owner,omitempty"`
	Spec        *string   `json:"spec,omitempty"`
	Tags        *[]string `json:"tags,omitempty"`
}

// Pagination defines model for Pagination.
type Pagination struct {
	Limit  *int `json:"limit,omitempty"`
	Offset *int `json:"offset,omitempty"`
	Total  *int `json:"total,omitempty"`
}

// Workload defines model for Workload.
type Workload struct {
	Description  *string `json:"description,omitempty"`
	Envinronment *string `json:"envinronment,omitempty"`
	Id           *string `json:"id,omitempty"`
	Name         *string `json:"name,omitempty"`
}

// AddLensRequest defines model for AddLensRequest.
type AddLensRequest = AddLensBody

// AddLensJSONRequestBody defines body for AddLens for application/json ContentType.
type AddLensJSONRequestBody = AddLensBody

// AddWorkloadJSONRequestBody defines body for AddWorkload for application/json ContentType.
type AddWorkloadJSONRequestBody = Workload
