// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package api

import (
	"github.com/katallaxie/service-lense/internal/models"
)

// BadRequest defines model for BadRequest.
type BadRequest = models.BadRequest

// Lens defines model for Lens.
type Lens = models.Lens

// Pagination defines model for Pagination.
type Pagination struct {
	Limit  *int `json:"limit,omitempty"`
	Offset *int `json:"offset,omitempty"`
	Total  *int `json:"total,omitempty"`
}

// Workload defines model for Workload.
type Workload = models.Workload

// AddLensJSONRequestBody defines body for AddLens for application/json ContentType.
type AddLensJSONRequestBody = Lens

// AddWorkloadJSONRequestBody defines body for AddWorkload for application/json ContentType.
type AddWorkloadJSONRequestBody = Workload
