import { paths, components } from './schema' // <- generated by openapi-typescript

// Lens is the type of the response body for the GET /lenses endpoint
type Lens = components['schemas']['Lens']

// Path params
// type EndpointParams = paths[]

// PostLensRequestBody is the type of the request body for the POST /lenses endpoint
type PostLensRequestBody = paths['/lenses']['post']['requestBody']

// AddLensResponse is the type of the response body for the POST /lenses endpoint
type AddLensResponse = paths['/lenses']['post']['responses'][200]['content']
